language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.4'

cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - cp bin/test/package.json .

after_success:
  - npm run coverage

after_script:
  - npm run remove-coverage

env:
  matrix:
    # Parallelize backend and fronted test
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
